name: Build Release APK

on:
  push:
    tags:  # 通常在打标签时构建发布版本
      - 'v*'
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: gradle

    - name: Prepare keystore
      run: |
        # 从GitHub Secrets创建签名文件
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > app/keystore.jks

    - name: Create signing config
      run: |
        # 创建签名配置文件
        cat > app/signing.properties << EOF
        storeFile=keystore.jks
        storePassword=${{ secrets.KEYSTORE_PASSWORD }}
        keyAlias=${{ secrets.KEY_ALIAS }}
        keyPassword=${{ secrets.KEY_PASSWORD }}
        EOF

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build release APK
      run: ./gradlew assembleRelease

    - name: Upload release APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release
        path: app/build/outputs/apk/release/app-release.apk

    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: app/build/outputs/apk/release/app-release.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}